### PR TITLE
[ADF-4075] TaskFormsApi - change getRestFieldValues return format

### PR DESCRIPTION
**Pull request by SilviuCPopa**
**Please check if the PR fulfills these requirements**
```
[x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[ ] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
https://issues.alfresco.com/jira/browse/ADF-4075

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by binduwavell** [comment]
JIRA describes problem. Please describe why/how this solves the problem.

**Comment by binduwavell** [comment]
If this is a public function then this function signature change may be a breaking change?

**Comment by binduwavell** [comment]
Given there is no test in this PR, I assume this code is not tested. Given that it was deemed to be wrong, it is a good candidate for a test showing the previous bad behavior that is now fixed by this change.

**Comment by eromano** [comment]
@binduwavell hi @SilviuCPopa is still working on it, I am talking with him he created the PR more to show to me the problem

**Comment by eromano** [comment]
the test and all the other thing will follow

**Comment by eromano** [comment]
Looking on the problem with @SilviuCPopa seems that there is a problem when the server returns an array that is not wrapped in an object. The modify needs properly to go in the deserializer

**Comment by binduwavell** [comment]
Thanks for explaining. If a PR is incomplete, would be great if it indicated that. If not filling out the top of the form is how we flag this and you will never merge a PR without this data, I am happy to live with that.

**Comment by eromano** [comment]
Nice idea i Created a label for it

**Comment by binduwavell** [comment]
@eromano so you merged incomplete work? Did you merge it into something that is also incomplete?

**Comment by eromano** [comment]
I just forgot to remove the label was all fine from my point of view, did you see something?

**Comment by binduwavell** [comment]
I guess you just forgot to remove the tag. If folks use the new WIP PR feature this should not happen.

**Pull request merged**
