### PR TITLE
[ACA-3492] - Expose new Groups Endpoints

### PR DESCRIPTION
**Pull request by dhrn**
**Please check if the PR fulfills these requirements**
```
[x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[ ] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

https://issues.alfresco.com/jira/browse/ACA-3492

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by DenysVuika** [comment]
Is this code generated from the swagger definition?

**Comment by dhrn** [comment]
No

**Comment by dhrn** [comment]
getting this error from code generator
`[ERROR] Failed to execute goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.20:generate (generate-core-api) on project alfresco-core-rest-api: Execution generate-core-api of goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.20:generate failed: Can't load config class with name typescript-node Available: aspnetcore
`

**Comment by DenysVuika** [comment]
@eromano ^^^

**Pull request merged**
