### PR TITLE
Issue 357 Add support for withCredentials

### PR DESCRIPTION
**Pull request by ajmas**
**Please check if the PR fulfills these requirements**
```
[x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[x] Tests for the changes have been added (for bug fixes / features)
[x] Docs have been added / updated (for bug fixes / features)
```

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

https://github.com/Alfresco/alfresco-js-api/issues/357

**What is the new behavior?**

Allows for sending credentials as part of a request.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by DenisVuyka** [comment]
@ajmas can you please change a PR to be against `development` branch

**Comment by DenisVuyka** [comment]
No worries, I've updated the PR.

**Comment by ajmas** [comment]
Apparently this is failing a check, but it is not clear what it is? The only suggestion I see is that it could be due to the modification of an existing line of code?

**Comment by DenisVuyka** [comment]
That does not seem to be related to your PR. We will check CI settings later. Thanks for your contribution! 👍

**Comment by dmoeyersons** [comment]
Is there an idea if and when this will be implemented in the master branch? This functionality would be a solution for Kerberos SSO authentication in ADF.
Thanks.

**Pull request merged**
