### PR TITLE
Add that node 12 is required in the readme

### PR DESCRIPTION
**Pull request by garth**
The build seems fail with later versions of node.

Also add volta config for a node version that currently works and can be updated when later node versions are supported.

**Please check if the PR fulfills these requirements**
```
[ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[ ] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by DenysVuika** [comment]
Using node 14.x and the project builds fine without any errors... why node 12 is needed and why newer versions won't work according to this PR?

**Comment by garth** [comment]
Dependency install fails for me on node@14. It's not a big issues, just switched to node 12 and everything works. Seems that you don't have which node versions are supported in the readme.

Feel free to reject this PR, but maybe consider to document node versions that do work somewhere. Of course it's always good to use volta for node and npm versions to be sure that everyone gets the same versions.

**Comment by DenysVuika** [comment]
Can you please give more details on what dependency is failing and what are the steps to reproduce? Note that when switching major node versions you need to remove node_modules and install everything again

**Comment by DenysVuika** [comment]
Closing as not an issue

**Pull request closed without merging**
