### PR TITLE
don't copy ts files to dist/package/src

### LINKED ISSUE #1083: PR #1081 does not fully fix type errors
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

In the build output, after #1081 was merged, type files (.d.ts) are now separated, but the generated .js and .map are still distributed alongside the original .ts files, which in some cases still causes the .ts versions to be picked up and errors are raised.

**Expected behavior:**

.ts files are probably not needed for npm package? but at least the build output should be restructured so that .d.ts, .js and .map files are together and .ts are separated.

**Steps to reproduce the issue:**

Reference `@alfresco/js-api` in unit tests (jest) and the following error is raised.

```
    SyntaxError: /Users/garth/Projects/ecs/ecs4/node_modules/@alfresco/js-api/src/api-legacy/legacy.ts: Unexpected token, expected "{" (104:7)

      102 |  * @deprecated 3.0.0
      103 |  */
    > 104 | export namespace Legacy {
          |        ^
      105 |     export interface Activiti {
      106 |         alfrescoApi: AlfrescoApiActiviti;
      107 |         aboutApi: AboutApi;

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:134:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:129:17)
      at Parser.raise (node_modules/@babel/parser/src/parser/error.js:78:17)
      at Parser.unexpected (node_modules/@babel/parser/src/parser/util.js:173:16)
      at Parser.parseExport (node_modules/@babel/parser/src/parser/statement.js:1760:16)
      at Parser.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:274:25)
      at Parser.parseStatement (node_modules/@babel/parser/src/parser/statement.js:176:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/src/parser/statement.js:910:25)
      at Parser.parseBlockBody (node_modules/@babel/parser/src/parser/statement.js:886:10)
      at Parser.parseProgram (node_modules/@babel/parser/src/parser/statement.js:74:10)
```

Remove the `legacy.ts` file and the error is gone (though the next alfresco .ts file found will raise).

**Node version (for build issues):**  

node: 15.14.0

**New feature request:**

### PR DESCRIPTION
**Pull request by garth**
fixes #1083

**Please check if the PR fulfills these requirements**
```
[ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[ ] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```

**What kind of change does this PR introduce?** (check one with "x")
```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by eromano** [comment]
I don't think is needed because src is in the npmignore

**Comment by garth** [comment]
With beta 30 installed via npm the src ts files are still there.

**Comment by eromano** [comment]
with npm works, yes probably in link scenario nope

**Comment by eromano** [comment]
good point

**Review by eromano — APPROVED** [review]

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-js-api/pull/1113 moved here in order to let the CI run

**Pull request closed without merging**
